#!/bin/tcsh -xef

# ---------------------- set process variables ----------------------

set mask_dset = #Mask directory

set dirA = #Results directory

# specify and possibly create results directory
set results_dir = test.results
if ( ! -d $results_dir ) mkdir $results_dir

# ------------------------- process the data -------------------------

3dttest++ -Clustsim -prefix $results_dir/confident_vs_notconfident -AminusB -paired \
          -mask $mask_dset                                           \
          -setA confident                                            \
             02 "$dirA/s102.results/stats.s102+tlrc[7]"              \
             03 "$dirA/s103.results/stats.s103+tlrc[7]"              \
             04 "$dirA/s104.results/stats.s104+tlrc[7]"              \
             06 "$dirA/s106.results/stats.s106+tlrc[7]"              \
             #07 "$dirA/s107.results/stats.s107+tlrc[7]"              \
             08 "$dirA/s108.results/stats.s108+tlrc[7]"              \
             09 "$dirA/s109.results/stats.s109+tlrc[7]"              \
             10 "$dirA/s110.results/stats.s110+tlrc[7]"              \
             11 "$dirA/s111.results/stats.s111+tlrc[7]"              \
             12 "$dirA/s112.results/stats.s112+tlrc[7]"              \
             13 "$dirA/s113.results/stats.s113+tlrc[7]"              \
             14 "$dirA/s114.results/stats.s114+tlrc[7]"              \
             15 "$dirA/s115.results/stats.s115+tlrc[7]"              \
             16 "$dirA/s116.results/stats.s116+tlrc[7]"              \
          -setB notconfident                                         \
             02 "$dirA/s102.results/stats.s102+tlrc[10]"              \
             03 "$dirA/s103.results/stats.s103+tlrc[10]"              \
             04 "$dirA/s104.results/stats.s104+tlrc[10]"              \
             06 "$dirA/s106.results/stats.s106+tlrc[10]"              \
             #07 "$dirA/s107.results/stats.s107+tlrc[10]"              \
             08 "$dirA/s108.results/stats.s108+tlrc[10]"              \
             09 "$dirA/s109.results/stats.s109+tlrc[10]"              \
             10 "$dirA/s110.results/stats.s110+tlrc[10]"              \
             11 "$dirA/s111.results/stats.s111+tlrc[10]"              \
             12 "$dirA/s112.results/stats.s112+tlrc[10]"              \
             13 "$dirA/s113.results/stats.s113+tlrc[10]"              \
             14 "$dirA/s114.results/stats.s114+tlrc[10]"              \
             15 "$dirA/s115.results/stats.s115+tlrc[10]"              \
             16 "$dirA/s116.results/stats.s116+tlrc[10]"
